### ISSUE TITLE
Timer reaching 49 days

### ISSUE THREAD

**Issue by AndyMel** [RobTillaart/CountDown#11]
Thanks for the library!
If a countdown for 100 hours is started when millis()= 48 days, would there it be some issue ?

**Comment by RobTillaart** [comment]
@AndyMel 
You are referring to the overflow

Never tried, but it is relative easy to test by using **micros()** and a countdown of 20 minutes starting after an hour.
micros() will overflow after 42xx seconds  that is about 75 minutes. 
As the math and logic are the same it could be tested in less than 2 hours.

Does this help?

**Comment by RobTillaart** [comment]
@AndyMel 
A look into the code does not ring an alarm, duration is measured with subtraction as it should to prevent errors.

line 103++ in cpp  **void CountDown::calcRemaining()**

uint32_t t = millis() - startTime ==> as this is done unsigned an overflow of millis() wont affect  t  
then t is compared to ticks which is straightforward. and reset to zero when done.

**Comment by AndyMel** [comment]
Thanks @RobTillaart for your review!
I will test with micros() anyway as you suggested

**Comment by AndyMel** [comment]
With this code it's confirmed that no issue is triggered but counter does not reach 0..

CountDown CD(CountDown::MICROS);
`bool myflag=false;
void loop()
{
  if (millis() > (1*60*60*1000UL) && !myflag) //1 hour from boot
  {
    myflag=true;
    CD.start(20*60*1000UL*1000UL); //20 minutes (microseconds)
  } 
    if (CD.remaining()>0)
    {
    Serial.print("Remaining: ");
    Serial.print(CD.remaining()/1000/1000);
    Serial.println(" seconds ");
    delay(5000);
    }
}
`
/**/
Remaining: 914 seconds 
Remaining: 909 seconds 
Remaining: 904 seconds 
Remaining: **899** seconds 

Remaining: **1199** seconds 
Remaining: 1194 seconds 
Remaining: 1189 seconds 
Remaining: 1184 seconds 
/**/

**Comment by RobTillaart** [comment]
That sounds like a bug. 
To be investigate asap

**Comment by RobTillaart** [comment]
(updated your post for syntax highlighting - add 3 backquotes +cpp

**Comment by RobTillaart** [comment]
I'm going to run your sketch to see if I can replicate

**Comment by RobTillaart** [comment]
@AndyMel 
Patched the library with a hard offset of 4290.000.000 on the micros.
(replaced all calls to micros() to micros() + 4290 million,
This sets micros() just ~5 seconds before overflow

Also added a print statement in calcRemaining() to show the current value of micros().

Allows me to test overflow in < 20 seconds and it works as it should.

output 
```
COUNTDOWN_LIB_VERSION: 0.2.7
Remaining: 4290007560
9 seconds 
Remaining: 4291009688
8 seconds 
Remaining: 4292010516
7 seconds 
Remaining: 4293011340
6 seconds 
Remaining: 4294012168
5 seconds 
Remaining: 45692
4 seconds 
Remaining: 1046260
3 seconds 
Remaining: 2046940
2 seconds 
Remaining: 3047616
1 seconds 
Remaining: 4048288
0 seconds 
Remaining: 5048952
0 seconds 
```

Also works with 20 minutes

```cpp
COUNTDOWN_LIB_VERSION: 0.2.7
Remaining: 4290007560
1199 seconds 
Remaining: 4291009940
1198 seconds 
Remaining: 4292010920
1197 seconds 
Remaining: 4293011896
1196 seconds 
Remaining: 4294012876
1195 seconds 
Remaining: 46556
1194 seconds 
Remaining: 1047280
1193 seconds 
Remaining: 2048104
1192 seconds 
```

So I cannot replicate based upon the snippet of loop you posted. 
Can you post your whole sketch

**Comment by RobTillaart** [comment]
Tested with millis() worked also ..

```cpp
COUNTDOWN_LIB_VERSION: 0.2.7
Remaining: 4294960007
1199 seconds 
Remaining: 4294961009
1198 seconds 
Remaining: 4294962010
1197 seconds 
Remaining: 4294963011
1196 seconds 
Remaining: 4294964012
1195 seconds 
Remaining: 4294965013
1194 seconds 
Remaining: 4294966013
1193 seconds 
Remaining: 4294967015
1192 seconds 
Remaining: 719
1191 seconds 
Remaining: 1721
1190 seconds 
Remaining: 2721
1189 seconds 
Remaining: 3722
1188 seconds 
Remaining: 4722
1187 seconds 
Remaining: 5723
```

**Comment by AndyMel** [comment]
Thanks @RobTillaart , It sounds good!
I will try with the same code (platform IO). That is:
```
#include <Arduino.h>
#include "CountDown.h"

CountDown CD(CountDown::MICROS);

uint32_t start, stop;
unsigned long inicio;
bool myflag=false;

void setup()
{
  Serial.begin(115200);
  }

void loop()
{

  if (millis() > (1*60*60*1000UL) && !myflag) //1 hour 
  {
    myflag=true;
    CD.start(20*60*1000UL*1000UL); //20 minutes (microseconds)
  } 
    if (CD.remaining()>0)
    {
    Serial.print("Remaining: ");
    Serial.print(CD.remaining()/1000/1000);
    Serial.println(" seconds ");
    delay(5000);
    }
}
```

**Comment by RobTillaart** [comment]
looked at your logging 
```cpp
Remaining: 914 seconds
Remaining: 909 seconds
Remaining: 904 seconds
Remaining: 899 seconds

Remaining: 1199 seconds
Remaining: 1194 seconds
Remaining: 1189 seconds
Remaining: 1184 seconds
```
And it looks like the stopwatch is reset to 20 minutes again.

**Comment by RobTillaart** [comment]
Thanks for the code, gives no clue.
Q1: Which board do you use?
Q2: Can you try this variation? it moves the start of the count down to **setup()**

```cpp
#include <Arduino.h>
#include "CountDown.h"

CountDown CD(CountDown::MICROS);

void setup()
{
  Serial.begin(115200);
  while (millis() < (1*60*60*1000UL) );  //  wait 1 hour 

  // start countdown
  CD.start(20*60*1000UL*1000UL); //20 minutes (microseconds)
}

void loop()
{
    if ( CD.remaining() > 0 )
    {
      Serial.print("Remaining: ");
      Serial.print(CD.remaining()/1000/1000);
      Serial.println(" seconds ");
      delay(1000);
    }
}
```

**Comment by RobTillaart** [comment]
Did more tests and found a serious bug when using **start(days, hours, minutes)** 
- see #12

**Comment by AndyMel** [comment]
Q1: I use Mega 2560
Q2: With your code ,the counter reaches 0 correctly..

(It seems that starting the wait loop in the setup, works fine)

Remaining: 8 seconds 
Remaining: 7 seconds 
Remaining: 6 seconds 
Remaining: 5 seconds 
Remaining: 4 seconds 
Remaining: 3 seconds 
Remaining: 2 seconds 
Remaining: 1 seconds 
Remaining: 0 seconds

**Comment by RobTillaart** [comment]
Thanks for testing, so now is the question how your original sketch could go wrong.

One option is that CD.start() is called twice, so adding an extra print statement should show that.

If you have time for another testrun?
```cpp
#include <Arduino.h>
#include "CountDown.h"

CountDown CD(CountDown::MICROS);

bool myflag = false;

void setup()
{
  Serial.begin(115200);
  }

void loop()
{

  if ( (millis() > (1*60*60*1000UL)) && (!myflag)) //1 hour 
  {
    myflag=true;
    CD.start(20*60*1000UL*1000UL); //20 minutes (microseconds)
    Serial.println("START CALLED ");
  } 
    if (CD.remaining()>0)
    {
    Serial.print("Remaining: ");
    Serial.print(CD.remaining()/1000/1000);
    Serial.println(" seconds ");
    delay(5000);
    }
}
```

**Comment by RobTillaart** [comment]
Found a possible cause for your original sketch, _startTime is not initialized in the constructor, _remainder idem, _state idem.
Depending on the 'random' memory content, there might be unwanted side effects. 
I have not found a scenario that explains the failure of your initial sketch, but no initialization is wrong.

==> I will add initialization in the constructor (I add this to the PR I am making for the MINUTES bug).

```cpp
CountDown::CountDown(const enum Resolution res)
{
  //  _res = MILLIS;  //  set in setResolution
  //  _ticks = 0;     //  set in setResolution
  _state = CountDown::STOPPED;
  _remaining = 0;
  _startTime = 0;
  setResolution(res);
  stop();
}
```

**Comment by RobTillaart** [comment]
FYI the Arduino build-CI script I use for my libs has a bug that is under attention of its maintainer. 
So although the PR build fails it will be merged a.s.a.p.

**Comment by AndyMel** [comment]
Thanks @Rob, 
I have tested your code, it reachs to 0, correctly.. 

Remaining: 34 seconds 
Remaining: 29 seconds 
Remaining: 24 seconds 
Remaining: 19 seconds 
Remaining: 14 seconds 
Remaining: 9 seconds 
Remaining: 4 seconds 

Both codes are almost identical. I will try again with with my original sketch

**Comment by AndyMel** [comment]
I have tried several times with my first code. I don't know what happened. Now reachs 0

Remaining: 14 seconds 
Remaining: 9 seconds 
Remaining: 4 seconds

**Comment by RobTillaart** [comment]
Could been an electrical glitch (wires, power supply,...)?

**Comment by RobTillaart** [comment]
@AndyMel 
If you consider the issue solved, please close the issue. 
I will merge the PR in a few moments.

**Comment by AndyMel** [comment]
Sure, it was electrical glitch. I've checked 4-5 times, and all of them, the counter reachs 0
I apologize for the inconvenience..

Thanks Rob for your attention and your work!

**Comment by RobTillaart** [comment]
Welcome!
