### ISSUE TITLE
setResolution

### ISSUE THREAD

**Issue by WanaGo** [RobTillaart/CountDown#7]
Hi,
Thanks very much for making this, it made making a start/stop/resume demo so much easier and faster.

One thing is, in the table in your readme, it states to use setResolution(SECONDS) as an example, however SECONDS is not declared. I ended up doing setResolution(2) and that worked fine.

I made the assumption too that start(tick) when the resolution is set to seconds, means the tick value is in seconds - which I guess is the point. ie start(20) is 20 seconds. It wasn't 100% clear when I read the readme though, had to read it over a few times to pick up all the details. Its all there, just not 100% clear at first. Same for remaining(), if that is also then based on seconds if that is what the resolution is set for. Could be a little clearer, but otherwise brilliant stuff.

Thank you

**Comment by RobTillaart** [comment]
Please try **setResolution(COUNTDOWN::SECONDS)**
Should work.

SECONDS is an emum within the class and has implicit a value of 2 which you already found out.

**Comment by RobTillaart** [comment]
Maybe I should add an extra example.

**Comment by WanaGo** [comment]
**CountDown::SECONDS** worked (not caps though), thanks very much.

**Comment by RobTillaart** [comment]
> no caps...

True, expected you would figure that out after I posted.

other things missing in the library?
Or in other libs? Just let me know

**Comment by RobTillaart** [comment]
@WanaGo 
updated the readme to reflect the constants for **setResolution()** and added an extra example.
(no new version as core code did not change).
